//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Colours = new HashSet<Colour>();
            this.Engines = new HashSet<Engine>();
            this.Manufacturies = new HashSet<Manufactury>();
            this.Transmissions = new HashSet<Transmission>();
        }
    
        public int Id_car { get; set; }
        public string Name_car { get; set; }
        public decimal Price { get; set; }
        public int Consumption { get; set; }
        public int Doors { get; set; }
        public int Achievement { get; set; }
        public decimal Cub_capacity { get; set; }
        public int Seats { get; set; }
        public bool Delivery { get; set; }
        public Nullable<bool> Navigation { get; set; }
        public Nullable<bool> Climatisation { get; set; }
        public Nullable<bool> ABS { get; set; }
        public Nullable<bool> ESP { get; set; }
        public Nullable<bool> Leather_interior { get; set; }
        public Nullable<bool> Xenons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colour> Colours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Engine> Engines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufactury> Manufacturies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transmission> Transmissions { get; set; }
    }
}
